language: go
go:
  - 1.1
  - 1.2
services:
  - redis-server
before_script:
  - mysql -e "CREATE DATABASE goat"
  - mysql -e "UPDATE mysql.user SET password=PASSWORD('travis') WHERE user='travis'; FLUSH PRIVILEGES"
script:
  - go build -o bin/goat
  - ./bin/goat -test
  - go build -tags='ql' bin/goat
  - ./bin/goat -test
