language: go
go:
  - 1.1
  - 1.2
services:
  - redis-server
before_script:
  - mysql -e "CREATE DATABASE goat"
  - mysql goat < res/mysql/announce_log.sql
  - mysql goat < res/mysql/api_keys.sql
  - mysql goat < res/mysql/files.sql
  - mysql goat < res/mysql/files_users.sql
  - mysql goat < res/mysql/scrape_log.sql
  - mysql goat < res/mysql/users.sql
  - mysql goat < res/mysql/whitelist.sql
  - mysql -e "UPDATE mysql.user SET password=PASSWORD('travis') WHERE user='travis'; FLUSH PRIVILEGES"
script:
  - go test github.com/mdlayher/goat/goat/
  - go get github.com/kisielk/errcheck
  - errcheck github.com/mdlayher/goat/goat/
  - go build -o bin/goat
  - ./bin/goat -test
  - go build -tags='ql' -o bin/goat
  - ./bin/goat -test
